# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdeploy < Formula
  desc "Manage your Granted Approvals deployment."
  homepage "https://granted.dev/"
  version "0.12.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/gdeploy/v0.12.0/gdeploy_0.12.0_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ea447a27fedeb87c76bcd8cf6eb3253d01917843e49bd6ac7016c7000aa89f72"

      def install
        bin.install "gdeploy"
      end
    end
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/gdeploy/v0.12.0/gdeploy_0.12.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0345f96dc8ebfb3acbf4c64629be4c7cc70cfcff1b4593f2ec26d636742dddee"

      def install
        bin.install "gdeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/gdeploy/v0.12.0/gdeploy_0.12.0_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3201dcae5efc7d17687f21ba6f636ca2ba0eae9400da2f8bbca549cb5d0f2eea"

      def install
        bin.install "gdeploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/gdeploy/v0.12.0/gdeploy_0.12.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9b41b1292b5091f3ec28107f555a75f1b903d0d8ff1c12f425b8b299204fa2a2"

      def install
        bin.install "gdeploy"
      end
    end
  end
end
