# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Granted < Formula
  desc "The easiest way to access your cloud."
  homepage "https://granted.dev/"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/granted/v0.1.12/granted_0.1.12_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bf0e81f653799e42997b7a787982ab5bbe3fadba70133635eb68055a334bc458"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/granted/v0.1.12/granted_0.1.12_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5ff71774422abc8fc558e86cb3d15d5941b85f9736fb02072acf00277b60e489"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/granted/v0.1.12/granted_0.1.12_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "cf321ac55fa9df54b34c2edb0e85fefc2349f3a93a6cb387ec59dfbacabf2314"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/granted/v0.1.12/granted_0.1.12_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1cc96e670c2c74ccecd9d68f94b3844ca1f0ab238a3ef634f69fcaf9483e02a4"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
  end
end
