# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Granted < Formula
  desc "The easiest way to access your cloud."
  homepage "https://granted.dev/"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/granted/v0.1.17/granted_0.1.17_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "00caec05e06c95509624c6fdbb19e2bdfaf5b525e1292388ce9f2815007449ad"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/granted/v0.1.17/granted_0.1.17_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a0226c7256151df68dde69fc5637ba76e82958277c668a201cceb7570c17aba2"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/granted/v0.1.17/granted_0.1.17_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c25b56e7f879e56d545dae6e75f99aa02a8940adf0952701a81e34d38a6a7cf5"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/granted/v0.1.17/granted_0.1.17_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fd15f9a941887cbe5d3c09752cda9ea25cdbbc0e72d2b06cac2f3daaee67b877"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
  end
end
