# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Granted < Formula
  desc "The easiest way to access your cloud."
  homepage "https://granted.dev/"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/granted/v0.1.13/granted_0.1.13_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "84e5658f0d8bf27f6cf511f63e7ee0ca12b7924839d8fe0307e00f67b22480a1"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
    if Hardware::CPU.arm?
      url "http://releases.commonfate.io/granted/v0.1.13/granted_0.1.13_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d2a53f00111a3ca9fa9438058dba23954e2f7c37f42cfd4dbc63c5ab1eeeca16"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://releases.commonfate.io/granted/v0.1.13/granted_0.1.13_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "098340a0e6b9f5ffbfe66ae2f2175e0b6e9fa473ac77dc9b7a7b9093ba5721e5"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
    if Hardware::CPU.intel?
      url "http://releases.commonfate.io/granted/v0.1.13/granted_0.1.13_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4318b30cdd21519d07d194b9f67057980d6447c9263b9d785d60d6491aac1f9a"

      def install
        bin.install "granted"
        bin.install "assumego"
        bin.install "assume"
        bin.install "assume.fish"
      end
    end
  end
end
